pulsar:
  volumes:
    persistence: true

  affinity:
    anti_affinity: false

  components:
    autorecovery: false
    pulsar_manager: true

  zookeeper:
    replicaCount: 1

  bookkeeper:
    replicaCount: 1
    configData:
      dbStorage_writeCacheMaxSizeMb: "32"
      dbStorage_readAheadCacheMaxSizeMb: "32"
      dbStorage_rocksDB_writeBufferSizeMB: "8"
      dbStorage_rocksDB_blockCacheSize: "8388608"

  broker:
    replicaCount: 1
    configData:
      autoSkipNonRecoverableData: "true"
      managedLedgerDefaultEnsembleSize: "1"
      managedLedgerDefaultWriteQuorum: "1"
      managedLedgerDefaultAckQuorum: "1"

  proxy:
    replicaCount: 1

  pulsar_manager:
    configData:
      ENV_SPRING_CONFIGURATION_FILE: "/pulsar-manager/pulsar-manager/application.properties"
      SPRING_CONFIGURATION_FILE: "/pulsar-manager/pulsar-manager/application.properties"
      PULSAR_MANAGER_OPTS: " -Dlog4j2.formatMsgNoLookups=true"
