services:
  pulsar:
    image: apachepulsar/pulsar:latest
    ports:
      - "6650:6650"
      - "8080:8080"
    command: bin/pulsar standalone
    healthcheck:
      test: [ "CMD", "bin/pulsar-admin", "brokers", "healthcheck" ]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - pulsar_data:/pulsar/data
      - pulsar_conf:/pulsar/conf

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: sensordb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - postgres

  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    depends_on:
      pulsar:
        condition: service_healthy
    environment:
      PULSAR_HOST: pulsar
      PULSAR_PORT: 6650
      PULSAR_URL: pulsar://pulsar:6650

  processor:
    build:
      context: .
      dockerfile: processor/Dockerfile
    depends_on:
      pulsar:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      PULSAR_HOST: pulsar
      PULSAR_PORT: 6650
      DB_HOST: postgres
      DB_PORT: 5432

volumes:
  pulsar_data:
  pulsar_conf:
  postgres_data:
  superset_data: