apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: iot-platform-stack
deploy:
  helm:
    releases:
      - name: iot-platform
        chartPath: ./helm/iot-platform
        namespace: iot-platform
        createNamespace: true
        upgradeOnChange: true
        wait: true