apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-credentials
  namespace: {{ .Values.clickhouse.namespace }}
  annotations:
   reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
   reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "iot-platform"
   reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
type: Opaque
# Can be strengthened: 
# https://github.com/Altinity/clickhouse-operator/blob/master/docs/security_hardening.md
stringData:
  username: admin
  password: clickhouse123
  password_sha256_hex: 2cca9d8714615f4132390a3db9296d39ec051b3faff87be7ea5f7fe0e2de14c9