# ===============================
# ConfigMap for PostgreSQL schema
# ===============================
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-schema
data:
  schema.sql: |
    CREATE TABLE sensor_data (
                                 id SERIAL PRIMARY KEY,
                                 sensor_id VARCHAR(50),
                                 temperature DOUBLE PRECISION,
                                 humidity DOUBLE PRECISION,
                                 timestamp TIMESTAMP,
                                 is_anomaly BOOLEAN
    );
