apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgres-schema
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
data:
  schema.sql: |
    {{ .Files.Get "files/schema.sql" | nindent 4 }}


