apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      initContainers:
        - name: wait-for-pulsar-proxy
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z pulsar-proxy.pulsar.svc.cluster.local 6650; do
                echo "waiting for pulsar-proxy";
                sleep 2;
              done;
        - name: wait-for-clickhouse
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z clickhouse-single.clickhouse.svc.cluster.local 9000; do
                echo "waiting for clickhouse-single";
                sleep 2;
              done;
      containers:
        - name: processor
          image: {{ .Values.processor.image.repository }}:{{ .Values.processor.image.tag }}
          env:
            {{- range $key, $value := .Values.processor.config }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            {{- toYaml .Values.processor.envFrom | nindent 10 }}