apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      # initContainers:
      #   - name: wait-for-pulsar-proxy
      #     image: busybox
      #     command:
      #       - sh
      #       - -c
      #       - |
      #         until nc -z pulsar-proxy.pulsar.svc.cluster.local 6650; do
      #           echo "waiting for pulsar-proxy";
      #           sleep 2;
      #         done;
      initContainers:
        - name: wait-for-proxy
          image: bitnami/kubectl
          command:
            - kubectl
            - wait
            - --for=condition=ready
            - pod/pulsar-proxy-0
            - -n
            - pulsar
            - --timeout=300s
      containers:
        - name: producer
          image: {{ .Values.producer.image.repository }}:{{ .Values.producer.image.tag }}
          env:
            {{- range $key, $value := .Values.producer.config }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}