apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pulsar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulsar
  template:
    metadata:
      labels:
        app: pulsar
    spec:
      containers:
        - name: pulsar
          image: {{ .Values.pulsar.image.repository }}:{{ .Values.pulsar.image.tag }}
          command: ["bin/pulsar", "standalone"]
          ports:
            - containerPort: 6650
            - containerPort: 8080
          readinessProbe:
            exec:
              command: ["bin/pulsar-admin", "brokers", "healthcheck"]
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          livenessProbe:
            exec:
              command: ["bin/pulsar-admin", "brokers", "healthcheck"]
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: pulsar-data
              mountPath: /pulsar/data
      volumes:
        - name: pulsar-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pulsar-data
---
apiVersion: v1
kind: Service
metadata:
  name: pulsar
spec:
  selector:
    app: pulsar

  ports:
    {{- range .Values.pulsar.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
